// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package sqlc

import ()

type Author struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Book struct {
	Isbn   string `json:"isbn"`
	Title  string `json:"title"`
	Author string `json:"author"`
}

type Review struct {
	ID       string `json:"id"`
	FullName string `json:"full_name"`
}
